services:
  web:
    command: python /root/code/Code/index.py
    image: peerapatst125842/a3
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8050:80
    env_file:
      - /.env
