version: '3.9'
services:
  web:
    command: python /root/code/Code/index.py
    image: peerapatst125842/a3:a2.0
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8050:80
#     labels:
#       # Allow Traefik to talk with your service
#       - traefik.enable=true
#       # Tell Traefik to use port 80
#       - traefik.http.services.web-st125842.loadbalancer.server.port=80
#       # This config you domain name. By default, your subdomain is web-st125842
#       # If you which to change the subdomain name, you uncomment the below configuration
#       - traefik.http.routers.web-st125842.rule=Host(`st125842.ml.brain.cs.ait.ac.th`)
#       # Below is for enable SSL.
#       - traefik.http.routers.web-st125842.tls=true
#       - traefik.http.routers.web-st125842.tls.certresolver=production
#       - traefik.http.routers.web-st125842.entrypoints=websecure
#     # This define network. You would need to keep it like this.
#     networks:
#       - default
#       - traefik_default

# # Keep it like this too.
# networks:
#   default:
#   traefik_default:
#     external: true
